Users & groups.
ork-a/pan_kanapka pull request #10
Opened 2019-04-29 17:38 UTC by ork-a

Użytkownicy i grupy.

2019-05-03 09:47 UTC, MarcinNowacki requested changes
Proszę o zmianę nazw modeli i pól na wersję PL. Z moją wiedzą nic więcej niestety nie byłem w stanie znaleźć. Za to dowiedziałem się trochę o komponentach do autentyfikacji (django.contrib.auth) :)

2019-05-03 09:47 UTC, MarcinNowacki commented on PanKanapka/clients/models.py
> +class Organization(models.Model):
nazwy modeli i pól powinny być po polsku

2019-05-03 09:47 UTC, MarcinNowacki commented on PanKanapka/clients/models.py
> +class Client(AbstractBaseUser):
nazwy modeli i pól powinny być po polsku

2019-05-05 21:31 UTC, PanBulka commented
Czy my trzymamy odzielnie modele dla klienta /folder clients i odzielnie modele dla reszty /folder bulka? Czy to nie powinno być razem? Mam poczucie, że wszystko się zduplikowało, chyba, że tak ma być

2019-05-06 18:26 UTC, ork-a commented
> Czy my trzymamy odzielnie modele dla klienta /folder clients i odzielnie modele dla reszty /folder bulka? Czy to nie powinno być razem? Mam poczucie, że wszystko się zduplikowało, chyba, że tak ma być

Z tego co ogarniam dobrze jest robić funkcjonalności jako osobne moduły (osobne apki współgrające ze sobą). Polecenie `manage.py startapp APP_NAME` tworzy nowy folder dla takiej apki, którą później wpina się w projekt. U nas projekt siedzi w folderze `PanKanapka`, `bulka` to są modele kanapek i składników, `clients` to są klienci - w sensie użytkownicy + organizacje (firmy).

Przy okazji chciałabym dopowiedzieć, że zostawiłam **umyślnie** część nazewnictwa po angielsku (nie modele i podstawowe pola), np. `password`. Wynika to z tego, że model `Uzytkownik` dziedziczy po modelu djangowym `AbstractBaseUser`, który ma zadeklarowane m. in. hasło (`password`) i metody z nim powiązane.

2019-05-06 18:46 UTC, KokonShifu commented
Z tego co zrozumiałem na zajęciach to chyba właśnie tak to ma wyglądać, jak
tlumaczysz. Żeby w razie co można to było przenieść do innego projektu itp.

Rozumiem, w takim razie pola typu ClientAdmin też wg tej myśli pozostały po
ang? Jeśli tak to ok.

Tomek

On Mon, 6 May 2019, 20:26 ork-a, <notifications@github.com> wrote:

> Czy my trzymamy odzielnie modele dla klienta /folder clients i odzielnie
> modele dla reszty /folder bulka? Czy to nie powinno być razem? Mam
> poczucie, że wszystko się zduplikowało, chyba, że tak ma być
>
> Z tego co ogarniam dobrze jest robić funkcjonalności jako osobne moduły
> (osobne apki współgrające ze sobą). Polecenie manage.py startapp APP_NAME
> tworzy nowy folder dla takiej apki, którą później wpina się w projekt. U
> nas projekt siedzi w folderze PanKanapka, bulka to są modele kanapek i
> składników, clients to są klienci - w sensie użytkownicy + organizacje
> (firmy).
>
> Przy okazji chciałabym dopowiedzieć, że zostawiłam *umyślnie* część
> nazewnictwa po angielsku (nie modele i podstawowe pola), np. password.
> Wynika to z tego, że model Uzytkownik dziedziczy po modelu djangowym
> AbstractBaseUser, który ma zadeklarowane m. in. hasło (password) i metody
> z nim powiązane.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ork-a/pan_kanapka/pull/10#issuecomment-489724506>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ALYWRBHNMSEWTFB7OUWTJP3PUBZ65ANCNFSM4HJFKA7A>
> .
>

2019-05-06 19:05 UTC, PanBulka commented
Ok, dzięki za odpowiedź :) a jakie konkretnie apki jeszcze będą? Jaka
struktura? Gdzie wrzucić templates do umieszczania formularzy?
Wiecie, ja całą wiedzę o djano czerpię z blogów jak to, a tu są same proste
przykłady:
http://yaizabailen.com/django-tutorial-creating-the-back-end-for-the-restaurant-picker-app/


pon., 6 maj 2019, 20:46 użytkownik KokonShifu <notifications@github.com>
napisał:

> Z tego co zrozumiałem na zajęciach to chyba właśnie tak to ma wyglądać, jak
> tlumaczysz. Żeby w razie co można to było przenieść do innego projektu itp.
>
> Rozumiem, w takim razie pola typu ClientAdmin też wg tej myśli pozostały po
> ang? Jeśli tak to ok.
>
> Tomek
>
> On Mon, 6 May 2019, 20:26 ork-a, <notifications@github.com> wrote:
>
> > Czy my trzymamy odzielnie modele dla klienta /folder clients i odzielnie
> > modele dla reszty /folder bulka? Czy to nie powinno być razem? Mam
> > poczucie, że wszystko się zduplikowało, chyba, że tak ma być
> >
> > Z tego co ogarniam dobrze jest robić funkcjonalności jako osobne moduły
> > (osobne apki współgrające ze sobą). Polecenie manage.py startapp APP_NAME
> > tworzy nowy folder dla takiej apki, którą później wpina się w projekt. U
> > nas projekt siedzi w folderze PanKanapka, bulka to są modele kanapek i
> > składników, clients to są klienci - w sensie użytkownicy + organizacje
> > (firmy).
> >
> > Przy okazji chciałabym dopowiedzieć, że zostawiłam *umyślnie* część
> > nazewnictwa po angielsku (nie modele i podstawowe pola), np. password.
> > Wynika to z tego, że model Uzytkownik dziedziczy po modelu djangowym
> > AbstractBaseUser, który ma zadeklarowane m. in. hasło (password) i metody
> > z nim powiązane.
> >
> > —
> > You are receiving this because your review was requested.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ork-a/pan_kanapka/pull/10#issuecomment-489724506>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe-auth/ALYWRBHNMSEWTFB7OUWTJP3PUBZ65ANCNFSM4HJFKA7A
> >
> > .
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ork-a/pan_kanapka/pull/10#issuecomment-489731029>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AL5PPGOGH53WNJNGPMSDRDDPUB4G7ANCNFSM4HJFKA7A>
> .
>

2019-05-12 06:02 UTC, MarcinNowacki approved these changes

2019-05-12 06:18 UTC, merged