Magdacwiklinska080527 sync
ork-a/pan_kanapka pull request #20
Opened 2019-05-08 20:33 UTC by magdacwiklinska

1) Do tabeli kanapki w bazie danych dodana kolumna z nazwami kanapek.
2) Baza danych uzupełniona danymi kanapki, składniki, alergeny i relacje pomiędzy nimi.
3) Zaktualizowany schemat bazy danych w pdf o dodaną kolumnę z nazwami kanapek.

Proszę o review.
Teraz zajmę się stworzeniem pliku CSV do uzupełnienia bazy danych.

2019-05-12 19:51 UTC, MarcinNowacki approved these changes

2019-05-12 20:02 UTC, ork-a commented
@magdacwiklinska 
Dobra robota, ale trzeba przed zmerdżowaniem rozwiązać konflikt.
Proponuję dodać db.sqlite3 do .gitignore i każdy sam będzie robił migracje.

2019-05-12 20:03 UTC, ork-a requested changes
Przed merdżem trzeba rozwiązać konflikt db.sqlite3.

2019-05-14 16:18 UTC, magdacwiklinska commented
Konflikty rozwiązane manualnie. Bazę danych chciałabym usunąć w osobnym commicie.  W tej chwili jest ona wypełniona danymi testowymi. Powinna być usunięta gdy Marcin napisze skrypt, który wypełnia bazę danymi z pliku CSV.

2019-05-16 17:44 UTC, merged